# Use official Node.js image as the base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install
RUN npm i stripe

# Copy the rest of the application files
COPY . .

RUN npm install @prisma/client
RUN npx prisma generate

# Build the Next.js app
RUN npm run build

# Expose the port that Next.js will run on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]
