version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./firebase:/app/firebase
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
